import Head from "next/head";
import { IHeadProps } from "../../interfaces/IHeadProps";

const HeadComponent = ({ title }: IHeadProps) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HeadComponent;
